### PR TITLE
Add ruby-irb alpine package

### PR DESCRIPTION
**Pull request by chingor13**
This will install ruby-irb into our base ruby images so that you can run rails console in the container.

### CODE REVIEW

**Comment by remkade** [comment]
I would argue that we should leave this out, and just document how to install this package in the case of debugging.

I'd prefer to err on the side of lean personally.

**Comment by dplummer** [comment]
I agree. If someone needs to run a console command they can probably just run `apk add ruby-irb`

**Comment by bluetwin** [comment]
I feel this could be more helpful if we make this simple instead of having to install ruby-irb to debug. @dplummer how do you handle debugging in Elixir?

**Comment by sringling** [comment]
@dplummer @remkade I'd like to see this happen - apk add is a command we have to memorize and enter every time we want to rails c something and this makes it simpler.  Do you really want to tell every single current and future employee they should memorize that command and enter it in every single time they need to debug anything ever in any rancher instance?  Is there a concrete size metric that is bothersome about the inclusion of this library?

**Comment by remkade** [comment]
We should be able to have a message of the day printed by the shell when
you login.

The size of the container directly impacts production deployment time and
sometimes reliability. I'd rather forgo a library that is used occasionally
for debugging if we can simply have a helpful motd explaining basic
debugging stuff (which we should add either way).

**Comment by dplummer** [comment]
+1 for motd, that's a great idea

@bluetwin: for Elixir the compiled binary includes the console, so (for say StrangerForces) you can run `./app/bin/stranger_forces console` to get the repl. Since its a compiled image it isn't possible to add the console later. Fortunately due to the compiling process we use our docker images are ~30MB for Elixir projects :)

**Review by azuretek — APPROVED** [review]

**Review by matsadler — APPROVED** [review]
:+1:

While I would also want to keep images smaller, irb is tiny, and there's a bunch of other huge not-always-necessary packages included here, so I don't think that argument passes muster in this case.

**Pull request merged**
